services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    user.data.create_account.rest_controller:
        public: true
        class: User\Data\UserInterface\Rest\CreateAccount
        arguments:
            - '@shared.command.bus'

    user.data.update_account.rest_controller:
        public: true
        class: User\Data\UserInterface\Rest\UpdateAccount
        arguments:
            - '@shared.command.bus'

    user.data.orm.repository:
        class: User\Data\Infrastructure\Repository\UserDataRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    user.data.account_creator.handler:
        class: User\Data\Application\Action\Command\AccountCreator
        tags:
            name: messenger.message_handler
            handles: User\Data\Application\Model\Command\CreateAccountModel
        arguments:
            - '@user.data.orm.repository'

    user.data.account_updater.handler:
        class: User\Data\Application\Action\Command\AccountUpdater
        tags:
            name: messenger.message_handler
            handles: User\Data\Application\Model\Command\UpdateAccountModel
        arguments:
            - '@user.data.orm.repository'