services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    user.group.create_group.rest_controller:
        public: true
        class: User\Group\UserInterface\Rest\CreateGroup
        arguments:
            - '@shared.command.bus'

    user.data.group_creator.handler:
        class: User\Group\Application\Action\Command\GroupCreator
        tags:
            name: messenger.message_handler
            handles: User\Group\Application\Model\Command\GroupData
        arguments:
            - '@shared.query.bus'
            - '@shared.persistence.repository'

    user.group.show_group_list.rest_controller:
        public: true
        class: User\Group\UserInterface\Rest\ShowGroupList
        arguments:
            - '@shared.query.bus'

    user.data.group_list_finder.handler:
        class: User\Group\Application\Action\Query\GroupListFinder
        tags:
            name: messenger.message_handler
            handles: User\Group\Application\Model\Query\GroupList
        arguments:
            - '@user.group.orm.repository'

    user.group.show_group_data.rest_controller:
        public: true
        class: User\Group\UserInterface\Rest\ShowGroupDada
        arguments:
            - '@shared.query.bus'

    user.data.group_data_finder.handler:
        class: User\Group\Application\Action\Query\GroupDataFinder
        tags:
            name: messenger.message_handler
            handles: User\Group\Application\Model\Query\GroupData
        arguments:
            - '@user.group.orm.repository'

    user.data.group_finder.handler:
        class: User\Group\Application\Action\Query\GroupFinder
        tags:
            name: messenger.message_handler
            handles: User\Group\Application\Model\Query\Group
        arguments:
            - '@user.group.orm.repository'

    user.group.update_group.rest_controller:
        public: true
        class: User\Group\UserInterface\Rest\UpdateGroup
        arguments:
            - '@shared.command.bus'

    user.data.group_updater.handler:
        class: User\Group\Application\Action\Command\GroupUpdater
        tags:
            name: messenger.message_handler
            handles: User\Group\Application\Model\Command\GroupNewData
        arguments:
            - '@shared.query.bus'
            - '@shared.persistence.repository'

    user.group.orm.repository:
        class: User\Group\Infrastructure\Repository\UserGroupRepository
        arguments:
            - '@doctrine.orm.entity_manager'