services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    user.data.create_account.rest_controller:
        public: true
        class: User\Data\UserInterface\Rest\CreateAccount
        arguments:
            - '@shared.command.bus'

    user.data.orm.repository:
        class: User\Data\Infrastructure\Repository\UserDataRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    user.data.user_data_manager.handler:
        class: User\Data\Application\Action\Command\UserDataManager
        tags:
            name: messenger.message_handler
            handles: User\Data\Application\Model\Command\UserDataModel
        arguments:
            - '@user.data.orm.repository'