doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            account_uuid: User\Account\Infrastructure\Util\Orm\Type\AccountUuidType
            user_group_uuid: User\Group\Infrastructure\Util\Orm\Type\UserDataUuidType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User\Account:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/User/Account/Infrastructure/Mapping/Orm'
                prefix: 'User\Account\Domain\Entity'
                alias: User\Account
            User\Group:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/User/Group/Infrastructure/Mapping/Orm'
                prefix: 'User\Group\Domain\Entity'
                alias: User\Group

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
