security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'argon2i'
    providers:
        app_user_provider:
            entity:
                class: User\Account\Domain\Entity\Account
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                success_handler: shared.security.success_authentication
                failure_handler: shared.security.failure_authentication
            logout:
                path: /logout
    role_hierarchy:
        ROLE_MANAGER: ROLE_DEVELOPER
        ROLE_ADMINISTRATOR: ROLE_MANAGER

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: argon21
                cost: 4
                time_cost: 3
                memory_cost: 10