framework:
    validation:
        email_validation_mode: html5
        mapping:
            paths:
                - '%kernel.project_dir%/src/User/Data/Infrastructure/Mapping/Validator/'
                - '%kernel.project_dir%/src/User/Group/Infrastructure/Mapping/Validator/'

when@test:
    framework:
        validation:
            not_compromised_password: false
