security_login:
    path: /login
    methods: POST

user_account:
    resource: ../src/User/Account/Infrastructure/Mapping/Routing/
    type: directory

user_group:
    resource: ../src/User/Aggregate/Infrastructure/Mapping/Routing/
    type: directory
