services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    shared.request.param_converter:
        class: Shared\Infrastructure\Adapter\ParamConverter\RequestParamConverter
        tags:
            - request.param_converter

    shared.orm.repository:
        class: Shared\Infrastructure\Repository\SharedRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    shared.persistence.repository:
        class: Shared\Infrastructure\Repository\PersistenceRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    shared.unique_value.validator:
        class: Shared\Application\Action\Validator\UniqueValueChecker
        autoconfigure: true
        arguments:
            - '@shared.orm.repository'

    shared.command.bus:
        class: Shared\Infrastructure\Proxy\MessageBus\CommandBus
        arguments:
            - '@command.bus'

    shared.query.bus:
        class: Shared\Infrastructure\Proxy\MessageBus\QueryBus
        arguments:
            - '@query.bus'

    shared.event.kernel_exception.listener:
        class: Shared\Infrastructure\EventListener\KernelException
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    shared.event.success_login.listener:
        class: Shared\Infrastructure\EventListener\Security\SuccessLogin
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LoginSuccessEvent, method: onSuccess }

    shared.event.failure_login.listener:
        class: Shared\Infrastructure\EventListener\Security\FailureLogin
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LoginFailureEvent, method: onFailure }

    shared.event.logout.listener:
        class: Shared\Infrastructure\EventListener\Security\Logout
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LogoutEvent, method: onLogout }