services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    shared.request.param_converter:
        class: Shared\Infrastructure\Adapter\ParamConverter\RequestParamConverter
        tags:
            - request.param_converter

    shared.orm.repository:
        class: Shared\Infrastructure\Repository\SharedRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    shared.persistence.repository:
        class: Shared\Infrastructure\Repository\PersistenceRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    shared.unique_value.validator:
        class: Shared\Application\Action\Validator\UniqueValueChecker
        autoconfigure: true
        arguments:
            - '@shared.orm.repository'

    shared.command.bus:
        class: Shared\Infrastructure\Proxy\MessageBus\CommandBus
        arguments:
            - '@command.bus'

    shared.query.bus:
        class: Shared\Infrastructure\Proxy\MessageBus\QueryBus
        arguments:
            - '@query.bus'

    shared.event.kernel_exception.listener:
        class: Shared\Infrastructure\EventListener\KernelException
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    shared.security.user_provider:
        class: Shared\Infrastructure\Proxy\Security\UserProvider
        arguments:
            - '@doctrine'
            - User\Account\Domain\Entity\Account
            - email

    shared.event.success_authentication.listener:
        class: Shared\Infrastructure\EventListener\Security\SuccessAuthentication
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onSuccess }

    shared.event.failure_authentication.listener:
        class: Shared\Infrastructure\EventListener\Security\FailureAuthentication
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onFailure }

    shared.event.token_invalid.listener:
        class: Shared\Infrastructure\EventListener\Security\TokenInvalid
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onInvalid }

    shared.event.token_not_found.listener:
        class: Shared\Infrastructure\EventListener\Security\TokenNotFound
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onNotFound }

    shared.event.token_expired.listener:
        class: Shared\Infrastructure\EventListener\Security\TokenExpired
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onExpired }